name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

  build_upload_release_assets:
    name: Build & Upload Release Assets
    needs: create_release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]
    steps:
      - uses: actions/checkout@v2
      - name: Get App Version
        id: get_version
        run: |
          echo "::set-env name=APP_VERSION::$(sed -e 's/"//g' <<< cat build.gradle | grep 'version = ' | cut -d'=' -f2 | awk '{$1=$1};1')"
      - name: Set up JDK
        id: setup_jdk
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Cache Gradle packages
        id: cache_gradle_packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        id: build_gradle
        run: |
          ./gradlew build
      - name: Upload Release Asset
        id: upload_release_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/libs/com.github.lgdd.liferay.health-${{ env.APP_VERSION }}.jar
          asset_name: com.github.lgdd.liferay.health-${{ env.APP_VERSION }}-jdk${{ matrix.java }}.jar
          asset_content_type: application/octet-stream
